version: '3'

services:
  fastapi:
    build: api/segmentation
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi

  ui:
    build: ui/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: ui

networks:
  deploy_network:
    driver: bridge